### ISSUE TITLE
Cannot read property 'id' of null

### ISSUE THREAD

**Issue by foorb** [nebulade/meemo#49]
Maybe you can give me a hint whats the problem here?
```
Email receiving is enabled
/home/user/meemo/src/mail.js:191
                        logic.add(result.id, body, [], function (error) {
                                        ^

TypeError: Cannot read property 'id' of null
    at /home/user/meemo/src/mail.js:191:41
    at Object.profile (/home/user/meemo/src/users.js:97:40)
    at /home/user/meemo/src/mail.js:184:27
    at EventEmitter.<anonymous> (/home/user/meemo/src/mail.js:133:9)
    at EventEmitter.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:185:7)
    at /home/user/meemo/node_modules/imap/lib/Connection.js:1524:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by nebulade** [comment]
The issue is that whatever was extracted as the username from the mail is not be found in the user listing. Basically the email is `username@domain.tld` where username is the key in the object in the `.users.json` file.

Does that help?
