### ISSUE TITLE
Crash with latest meemo release

### ISSUE THREAD

**Issue by gramakri** [nebulade/meemo#56]
```
ERROR 'undefined' === 'string' [ /app/code/node_modules/connect-lastmile/lib/index.js:53:17 ] 
name:             AssertionError
actual:           undefined
expected:         string
operator:         ===
message:          'undefined' === 'string'
generatedMessage: true
stack: 
  """
    AssertionError: 'undefined' === 'string'
        at Object.profile (/app/code/src/users.js:57:12)
        at profile (/app/code/src/routes.js:125:11)
        at Layer.handle [as handle_request] (/app/code/node_modules/express/lib/router/layer.js:95:5)
        at next (/app/code/node_modules/express/lib/router/route.js:131:13)
        at /app/code/src/routes.js:66:9
        at /app/code/src/database/tokens.js:34:9
        at handleCallback (/app/code/node_modules/mongodb/lib/utils.js:95:56)
        at /app/code/node_modules/mongodb/lib/cursor.js:852:16
        at handleCallback (/app/code/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
        at setCursorDeadAndNotified (/app/code/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:506:3)
  """
```

**Comment by gramakri** [comment]
This happens if you are logged in with the older version. Workaround is to do `localstorage.clear()` in the browser developer console.
