### ISSUE TITLE
LDAP Auth - Duplicate entries found

### ISSUE THREAD

**Issue by Frankstar** [nebulade/meemo#76]
If im using the Local AUTH File everything is fine.

LDAP Config:

```
Environment=LDAP_BIND_DN=CN=ldapconnect,CN=Users,DC=domain,DC=local
Environment=LDAP_BIND_PASSWORD=password
Environment=LDAP_USERS_BASE_DN=OU=users,OU=someou,DC=domain,DC=local
Environment=LDAP_URL=ldap://10.0.0.20:389
```

Error Code: 

 ```
ERROR Internal error [ /opt/jsapps/meemo/_modules/connect-lastmile/lib/index.js:3:5 ]
  stack:
  """
  HttpError: Internal error
  at /opt/jsapps/meemo/src/routes.js::3
  at /opt/jsapps/meemo/src/users.js:3:
  at EventEmitter.<anonymous> (/opt/jsapps/meemo/src/users.js::5)
  at emitOne (events.js::13)
  at EventEmitter.emit (events.js:188:)
  at sendResult (/opt/jsapps/meemo/_modules/ldapjs/lib/client/client.js:138:)
  at messageCallback (/opt/jsapps/meemo/_modules/ldapjs/lib/client/client.js:141:1)
  at Parser.onMessage (/opt/jsapps/meemo/_modules/ldapjs/lib/client/client.js:108:14)
  at emitOne (events.js::13)
  at Parser.emit (events.js:188:)
  """
  name:          HttpError
  status:        500
  message:       Internal error
  internalError:
  """
  stack:
  """
  Error: Duplicate entries found
  at EventEmitter.<anonymous> (/opt/jsapps/meemo/src/users.js::1)
  at emitOne (events.js::13)
  at EventEmitter.emit (events.js:188:)
  at sendResult (/opt/jsapps/meemo/_modules/ldapjs/lib/client/client.js:138:)
  at messageCallback (/opt/jsapps/meemo/_modules/ldapjs/lib/client/client.js:141:1)
  at Parser.onMessage (/opt/jsapps/meemo/_modules/ldapjs/lib/client/client.js:108:14)
  at emitOne (events.js::13)
  at Parser.emit (events.js:188:)
  at Parser.write (/opt/jsapps/meemo/_modules/ldapjs/lib/messages/parser.js:11:8)
  at Socket.onData (/opt/jsapps/meemo/_modules/ldapjs/lib/client/client.js:10:)
  """
  code:    internal error
  message: Duplicate entries found
  """
```

**Comment by nebulade** [comment]
This actually was a wrong error message. You may want to check the specified ldap filter, which currently is hardcoded to:
```
filter: '(|(uid=' + identifier + ')(mail=' + identifier + ')(username=' + identifier + '))'
```
where `identifier` is the string entered in the login form here.
