### ISSUE TITLE
`npm install` fails on Windows

### ISSUE THREAD

**Issue by mohsentaleb** [nebulade/meemo#90]
Log:

```console
C:\wwwRoot\meemo
λ  npm i

> dtrace-provider@0.8.6 install C:\wwwRoot\meemo\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js


C:\wwwRoot\meemo\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\wwwRoot\meemo\node_modules\dtrace-provider
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> node-sass@3.13.1 install C:\wwwRoot\meemo\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\wwwRoot\meemo\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\wwwRoot\meemo\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\wwwRoot\\meemo\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 C:\msys64\usr\bin\python2.EXE
gyp verb check python version `C:\msys64\usr\bin\python2.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.11\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.10.0
gyp verb command install [ '8.10.0' ]
gyp verb install input version string "8.10.0"
gyp verb install installing version: 8.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.10.0
gyp verb build dir attempting to create "build" dir: C:\wwwRoot\meemo\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\wwwRoot\meemo\node_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\wwwRoot\meemo\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\wwwRoot\meemo\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\wwwRoot\meemo\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\msys64\usr\bin\python2.EXE
gyp info spawn args [ 'C:\\wwwRoot\\meemo\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\wwwRoot\\meemo\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\wwwRoot\\meemo\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Mohsen\\.node-gyp\\8.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Mohsen\\.node-gyp\\8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\wwwRoot\\meemo\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Mohsen\\.node-gyp\\8.10.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\wwwRoot\\meemo\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\wwwRoot\\meemo\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\wwwRoot\meemo\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\wwwRoot\meemo\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\wwwRoot\\meemo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\wwwRoot\meemo\node_modules\node-sass
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mohsen\AppData\Roaming\npm-cache\_logs\2019-02-14T14_59_23_798Z-debug.log
```

**Comment by Frankstar** [comment]
there are so many errors, what to you expect from this issue?
would investigate into `ImportError: No module named gyp`

**Comment by nebulade** [comment]
The gyp error should be ok, it is only optional and dtrace is not relevant for using meemo. The real issue is the missing pre-built node-sass. Not sure yet why that is the case, maybe we have to update the sass module for meemo?

**Comment by nebulade** [comment]
I updated the toplevel dependency for node-sass, which was gulp-sass with 86e553de742d6be18a8b104bac1bc415983acc6e 

@Frankstar can you try again, I hope this fixes it. Unfortunately I don't have access to a windows machine to test this

**Comment by Frankstar** [comment]
well, i would but i dont have a windows machine either :D
@mohsentaleb can you pls try again?

**Comment by nebulade** [comment]
Oh right, sorry for the wrong mentioning ;-)

**Comment by mohsentaleb** [comment]
node-sass seems to be fixed, but there's still some errors regarding `dtrace-provider`.

```console
C:\wwwRoot\meemo\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs
\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebui
ld )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .N
ET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the s
ystem path if it is installed elsewhere.  [C:\wwwRoot\meemo\node_modules\dtrace-provider\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\b
uild.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\wwwRoot\meemo\node_modules\dtrace-provider
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> node-sass@4.11.0 install C:\wwwRoot\meemo\node_modules\node-sass
> node scripts/install.js
```

@nebulade

**Comment by nebulade** [comment]
dtrace is only for unix systems anyways and is optional, so I assume you are not blocked by this anymore?

**Comment by mohsentaleb** [comment]
Yeah, I guess not. Thanks.
@nebulade
